pipeline:
  buildjar:
    image: maven:3.2-jdk-8
    commands:
      - mvn -q -DskipTests package
  buildimage:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build
         --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA
         --label build-number=$DRONE_BUILD_NUMBER
         --label build-date="$(date)"
         -t devopsbootcamp2/devcamp:$DRONE_COMMIT_SHA .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run devopsbootcamp2/devcamp /test.sh
  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u mgopaul -p $PASS
      - docker tag devopsbootcamp2/devcamp:$DRONE_COMMIT_SHA devopsbootcamp2/devcamp:production
      - docker push devopsbootcamp2/devcamp:$DRONE_COMMIT_SHA
      - docker push devopsbootcamp2/devcamp:production
  notify:
    when:
        status: [failure]
    image: amouat/network-utils
    commands: 
       - chmod +x ./notifysuccessfailure.sh
       - ./notifysuccessfailure.sh
  finish:
    image: debian
    commands: 
      - date

 
