pipeline:
  buildjar:
    image: maven:3.2-jdk-8
    commands:
      - mvn -q -DskipTests package
  buildimage:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build
         --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA
         --label build-number=$DRONE_BUILD_NUMBER
         --label build-date="$(date)"
         -t devopsbootcamp2/devcamp:$DRONE_COMMIT_SHA .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker kill test || true
      - docker rm test || true
      - docker create --name test devopsbootcamp2/devcamp:$DRONE_COMMIT_SHA
      - docker cp ./test.sh test:/test.sh
      - docker start test /test.sh
  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u mgopaul -p $PASS
      - docker tag devopsbootcamp2/devcamp:$DRONE_COMMIT_SHA devopsbootcamp2/devcamp:production
      - docker push devopsbootcamp2/devcamp:$DRONE_COMMIT_SHA
      - docker push devopsbootcamp2/devcamp:production
  deploy:
    image: devopsbootcamp2/ssh-drone-plugin
    environment:
      - SSH_USER=${SSH_USER}
      - SSH_KEY=/data/keys/swarm_master_ssh_key
      - SSH_COMMAND=~/deploy_api.sh
      - SSH_HOST=${SSH_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/keys:/data/keys
  notify:
    when:
        status: [failure]
    image: amouat/network-utils
    commands: 
       - chmod +x ./notifysuccessfailure.sh
       - ./notifysuccessfailure.sh
  finish:
    image: debian
    commands: 
      - date

 
